export const messages = [
  {
    id: "1",
    uid: "624e4b4dfc13ae695f000000",
    user: "adebruyn0",
    email: "gviner0@youtube.com",
    text: "vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra",
    createAt: "11/19/2021",
  },
  {
    id: "2",
    uid: "1",
    user: "kmenhci1",
    email: "oscougall1@freewebs.com",
    text: "mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum",
    createAt: "8/22/2021",
  },
  {
    id: "3",
    uid: "624e4b4dfc13ae695f000002",
    user: "hsaddleton2",
    email: "fmarques2@gizmodo.com",
    text: "consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris",
    createAt: "4/7/2021",
  },
  {
    id: "4",
    uid: "624e4b4dfc13ae695f000003",
    user: "pmaxwell3",
    email: "jnormanell3@dot.gov",
    text: "vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec",
    createAt: "10/29/2021",
  },
  {
    id: "5",
    uid: "624e4b4dfc13ae695f000004",
    user: "jcommuzzo4",
    email: "nriha4@ehow.com",
    text: "turpis elementum ligula vehicula consequat morbi a ipsum integer a",
    createAt: "2/11/2022",
  },
  {
    id: "6",
    uid: "624e4b4dfc13ae695f000005",
    user: "hivannikov5",
    email: "mmaulkin5@usatoday.com",
    text: "hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci",
    createAt: "8/5/2021",
  },
  {
    id: "7",
    uid: "624e4b4dfc13ae695f000006",
    user: "dslaymaker6",
    email: "dsteely6@mozilla.org",
    text: "suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique",
    createAt: "9/7/2021",
  },
  {
    id: "8",
    uid: "624e4b4dfc13ae695f000007",
    user: "ncarlson7",
    email: "kmacgarvey7@seesaa.net",
    text: "arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci",
    createAt: "8/15/2021",
  },
  {
    id: "9",
    uid: "624e4b4dfc13ae695f000008",
    user: "dhitzke8",
    email: "lweddup8@unblog.fr",
    text: "integer ac neque duis bibendum morbi non quam nec dui luctus rutrum",
    createAt: "1/17/2022",
  },
  {
    id: "10",
    uid: "624e4b4dfc13ae695f000009",
    user: "tarnout9",
    email: "mrawe9@diigo.com",
    text: "eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus",
    createAt: "3/12/2022",
  },
  {
    id: "11",
    uid: "624e4b4dfc13ae695f00000a",
    user: "jwinnetta",
    email: "mmartignonia@disqus.com",
    text: "primis in faucibus orci luctus et ultrices posuere cubilia curae",
    createAt: "1/3/2022",
  },
  {
    id: "12",
    uid: "624e4b4dfc13ae695f00000b",
    user: "wlinekerb",
    email: "dfishbourneb@slate.com",
    text: "mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse",
    createAt: "2/9/2022",
  },
  {
    id: "13",
    uid: "624e4b4dfc13ae695f00000c",
    user: "ctawtonc",
    email: "ssquibbesc@aboutads.info",
    text: "habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt",
    createAt: "3/6/2022",
  },
  {
    id: "14",
    uid: "624e4b4dfc13ae695f00000d",
    user: "abulpittd",
    email: "aclemensond@com.com",
    text: "dui vel sem sed sagittis nam congue risus semper porta volutpat",
    createAt: "8/4/2021",
  },
  {
    id: "15",
    uid: "624e4b4dfc13ae695f00000e",
    user: "miannuzzie",
    email: "bgreime@sun.com",
    text: "eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum",
    createAt: "6/2/2021",
  },
  {
    id: "16",
    uid: "624e4b4dfc13ae695f00000f",
    user: "ehorickf",
    email: "tgreensetf@hao123.com",
    text: "rhoncus sed vestibulum sit amet cursus id turpis integer aliquet",
    createAt: "10/3/2021",
  },
  {
    id: "17",
    uid: "624e4b4dfc13ae695f000010",
    user: "apaulingg",
    email: "rpiotrowskig@icio.us",
    text: "egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero",
    createAt: "9/11/2021",
  },
  {
    id: "18",
    uid: "1",
    user: "wpetherh",
    email: "nasipenkoh@booking.com",
    text: "sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis",
    createAt: "9/5/2021",
  },
  {
    id: "19",
    uid: "1",
    user: "nkeppyi",
    email: "cgerneri@imgur.com",
    text: "ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque",
    createAt: "11/17/2021",
  },
  {
    id: "20",
    uid: "1",
    user: "rrodsonj",
    email: "editterj@drupal.org",
    text: "in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus",
    createAt: "5/31/2021",
  },
];
